logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  datasource:
    url: jdbc:h2:mem:test_h2_db
    #    url: jdbc:h2:file:./test-db
    driverClassName: org.h2.Driver
    username: sa
    password: pass
  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console.enabled: true
  liquibase:
    change-log: classpath:db/changelog-main.xml

app:
  maze:
    max-size:
      rows: 50
      cols: 50
  solver:
    timeout: 5s
    threadCount: 5